version: '3.1'
services:
    mongo:
        build:
            context: ./mongo
        ports:
            - 27017:27017
        networks:
            - go-publish-subscribe
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: root
        networks:
            - go-publish-subscribe
    rabbitmq:
        build:
            context: ./rabbitmq
        ports:
            - 5672:5672
    rabbitmq-management:
        build:
            context: ./rabbitmq-management
        ports:
            - 8080:15672
        networks:
            - go-publish-subscribe    
        depends_on:
            - rabbitmq
    grafana:
        build:
            context: ./grafana
        ports:
            - 3000:3000
networks:
    go-publish-subscribe:
