version: '3.1'
services:
    mongo:
        build:
            context: ./mongo
        ports:
            - 27017:27017
        networks:
            - go-publish-subscribe
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: root
        networks:
            - go-publish-subscribe
    rabbitmq:
        build:
            context: ./rabbitmq
        ports:
            - 5672:5672
        networks:
            - go-publish-subscribe
    rabbitmq-management:
        build:
            context: ./rabbitmq-management
        ports:
            - 8080:15672
        networks:
            - go-publish-subscribe    
        depends_on:
            - rabbitmq
    grafana:
        build:
            context: ./grafana
        ports:
            - 3000:3000
        networks:
            - go-publish-subscribe
    loki:
        build:
            context: ./loki
        ports:
            - 3100:3100
        networks:
            - go-publish-subscribe
        depends_on:
            - grafana
    fluentd:
        build:
            context: fluentd
        ports:
            - 9880:9880
            - 24224:24224
        networks:
            - go-publish-subscribe
        depends_on:
            - loki
    publisher:
        build:
            context: publisher
        ports:
            - 1323:1323
        networks:
            - go-publish-subscribe
        depends_on:
            - rabbitmq
    subscribe-database:
        build:
            context: subscribe-database
        networks:
            - go-publish-subscribe
        depends_on:
            - mongo
    subscribe-file:
        build:
            context: subscribe-file
        networks:
            - go-publish-subscribe
    subscribe-logging:
        build:
            context: subscribe-logging
        networks:
            - go-publish-subscribe
        depends_on:
            - fluentd
networks:
    go-publish-subscribe:
